version: '2'

services:

  directeur:
    image: ubuntu:latest
    command: tail -F anything
    container_name: directeur
    dns: 51.77.141.217
    networks:
      direction: 
        ipv4_address: 172.20.1.66

  secretaire:
    image: ubuntu:latest
    command: tail -F anything
    container_name: secretaire
    dns: 51.77.141.217
    networks:
      direction: 
        ipv4_address: 172.20.1.67

  commercial1:
    image: ubuntu:latest
    command: tail -F anything
    container_name: commercial1
    dns: 51.77.141.217
    networks:
      commercial:
        ipv4_address: 172.20.1.18

  commercial2:
    image: ubuntu:latest
    command: tail -F anything
    container_name: commercial2
    dns: 51.77.141.217
    networks:
      commercial:
        ipv4_address: 172.20.1.19

  comptable1:
    image: ubuntu:latest
    command: tail -F anything
    container_name: comptable1
    dns: 51.77.141.217
    networks:
      comptable:
        ipv4_address: 172.20.1.34

  comptable2:
    image: ubuntu:latest
    command: tail -F anything
    container_name: comptable2
    dns: 51.77.141.217
    networks:
      comptable:
        ipv4_address: 172.20.1.35

  atelier:
    image: ubuntu:latest
    command: tail -F anything
    container_name: atelier
    dns: 51.77.141.217
    networks:
     atelier:
        ipv4_address: 172.20.1.50

networks:

  direction:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.64/28

  commercial:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.16/28

  comptable:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.32/28

  atelier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.48/28
